### ISSUE TITLE
imod - import CTF

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-imod#190]
This protocol is used to import CTF. However, it does not call to any imod problem. I  am sure there is a reason why it belongs to this repo. Due to it belongs to imod, its use is misleading because the user feels that it can be used for importing imod CTF  estimation, and not for ctffind gctf....

 Similarly occurs with importSetOfTM.

**Comment by azazellochg** [comment]
Hi @Vilax ! From the code I can see that you can only import IMOD's .defocus file, that's why I suppose it's here. Cistem plugin has it's own import tomo CTFs protocol.

In general, a lot of tomo code is based around imod as the basic software, and there's a lot of imod-specific code in the tomo core plugin. I agree it could be better arranged.

**Comment by Vilax** [comment]
I see, thanks @azazellochg

I could be useful to centralize the import-CTF in the same protocol, but I realize that it implies a major change with many dependencies... I will leave the topic open just in case someone else would like to add something else, but I understand now why it is in imod
