### ISSUE TITLE
Imod CTF seems to loose alignment information

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-imod#193]
The ctf correction loses the alignment information. I know this is not a good practice, but the alignment should be kept

![imagen](https://user-images.githubusercontent.com/12271438/228259467-d7b724d5-1bac-4c82-99a3-968783e4d64e.png)

Best

**Comment by azazellochg** [comment]
Hi, I've double checked and this is expected behaviour. If input TS have alignment information, they HAVE to be aligned before the correction takes place (see https://bio3d.colorado.edu/imod/doc/man/ctfphaseflip.html). Hence output CTF-corrected TS are aligned and have no associated alignment anymore.
